---
collections:
  - name: netbox.netbox
    source: https://galaxy.ansible.com
    version: 3.13.0
  - name: ansible.netcommon
    source: https://galaxy.ansible.com
    version: 2.5.1
  - name: ansible.utils
    source: https://galaxy.ansible.com
  - name: arista.cvp
    source: https://galaxy.ansible.com
  - name: arista.avd
    source: https://galaxy.ansible.com
  - name: arista.eos
    source: https://galaxy.ansible.com